### ISSUE TITLE
Cannot create different types of artifacts with the same name

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/mi-vscode#145] opened 2024-07-23 20:50 UTC
**Description:**

$subject.

Different artifact types cannot have the same name. 

<img width="80%" alt="vscode" src="https://github.com/user-attachments/assets/91aa4533-5ccd-48fb-ab68-695246b20157">

---

But in the integration studio creating different artifacts with the same name is possible.
<img width="80%" alt="integration-studio" src="https://github.com/user-attachments/assets/3156d714-7a99-4b06-89cb-0e1bd948d876">

---

**MI for VS Code Version:** v0.9.24071803 (pre-release)

---

**Steps to reproduce:**

1. Create an artifact (eg: sequence) and name it `Test`.
2. Create a different type of artifact (eg: API/message store/etc) and provide `Test` as the name.
 
Could observe this for several other artifact types as well.

**Comment by thuva9872** [comment] 2024-08-14 08:41
Hi @DinithiDiaz ,

This is the expected behaviour. MI expects each artifact to be with a unique name.

Thanks

**Comment by thuva9872** [comment] 2024-08-26 01:57
Closing this as it is not a bug. Please reopen if you have any more concerns.

**Closed by thuva9872** 2024-08-26 01:57 UTC
Labels: Resolution/Not a bug
