### ISSUE TITLE
Visual studio  Code  plugin for Micro Integrator 4.2.0

### ISSUE THREAD

**Issue by uarulraj486** [wso2/mi-vscode#10] opened 2024-06-10 11:09 UTC
I have already created this ticket in WSO2 -mi-internal. Please refer to the below ticket for more detail

**Comment by gigara** [comment] 2024-07-12 09:57
The issue is discussed in the internal repo. Closing this since it doesn't have any information provided.

**Closed by gigara** 2024-07-12 09:57 UTC
