### ISSUE TITLE
v0.9.24071803 Does not work at all 

### ISSUE THREAD

**Issue by OthmanMoukhli** [wso2/mi-vscode#131] opened 2024-07-22 13:21 UTC
**Description:**
The newest version of MI extension does not work at all: 
- when migrating a project from Integration Studio
- when opening a project already migrated using the older version of the extension 
-> The user can't see any artifacts
![image](https://github.com/user-attachments/assets/aa768ff6-de59-4b14-b213-ba2309447938)

**Suggested Labels:**
version, inconsistency

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24071803

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
> Migrate a project from Integration Studio to VSC MI extension 
OR 
> Open a Project from an older version of  VSC MI (e.g. [v0.9.24062409](https://github.com/wso2/mi-vscode/releases/tag/v0.9.24062409)) with the new version v0.9.24071803 

**Related Issues:**
#126

**Comment by hevayo** [comment] 2024-07-26 17:43
Hi @OthmanMoukhli can you try with 1.0.0 release. The issue might be due to project specific. We improved error recovery in the latest release.

**Comment by gigara** [comment] 2024-09-02 06:23
We're closing this as we couldn't reproduce the issue. Please reopen if it continues.

**Closed by gigara** 2024-09-02 06:23 UTC
Labels: Type/Bug, Severity/Blocker, Priority/Highest, Resolution/Cannot Reproduce
