### ISSUE TITLE
Error while launching run and debug: Build process failed - wso2 micro integrator with visual studio

### ISSUE THREAD

**Issue by JustinRaj-S** [wso2/mi-vscode#535] opened 2024-12-06 05:53 UTC
### Description

Hi Team,

I have installed WSO2 MI and Visual studio by follows WSO2 official site [https://mi.docs.wso2.com/en/latest/install-and-setup/install/installing-mi/](url)

I am trying the simple "Helloworld" service as instructed in WSO2 Quick reference [https://mi.docs.wso2.com/en/latest/get-started/quick-start-guide/](URL)

After designing the project, I am trying "Build and Run" to deploy the created service to the WSO2 MI Server.

However it always throws an ERROR saying `"Error while launching run and debug: Build process failed" `

`[MI Debug] [ERROR] Error executing BuildTask: Build process failed`

I updated visual studio by navigating to Help --> check for update and restart also done as per this reported issue [https://github.com/wso2/mi-vscode/issues/379](url)

However this issue is still persists. not able to resolve this. Can I get any guidance to resolve the same?

### Steps to Reproduce

Install WSO2 MI  by follows [https://mi.docs.wso2.com/en/latest/install-and-setup/install/installing-mi/](url)

Install Visual studio and add MI extension by follows [https://marketplace.visualstudio.com/items?itemName=WSO2.micro-integrator](url) 

Open Visual studio and created project as per this link [https://mi.docs.wso2.com/en/latest/get-started/quick-start-guide/](url)

after designing, click "Build and Run"

### Version

WSO2 MI 4.3.0 , Visual studio code: 1.95.3

### Environment Details (with versions)

OS: Windows 11
WSO2 MI 4.3.0 
Visual studio code: 1.95.3

**Comment by ChinthakaJ98** [comment] 2024-12-06 09:22
Closing this issue as it is a duplicate of https://github.com/wso2/mi-vscode/issues/534

**Closed by ChinthakaJ98** 2024-12-06 09:22 UTC
Labels: Type/Bug, Resolution/Duplicate
