### ISSUE TITLE
Wrong default values in HTTP inbound from

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/mi-vscode#293] opened 2024-08-01 03:58 UTC
**Description:**
In Advanced Properties **Worker Pool Size - Core** Should be less than **Worker Pool Size - Max**. if not it will give an error
```log
[2024-08-01 09:25:59,606] ERROR {SourceHandler} - Unexpected error: null java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1293)
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1215)
	at org.apache.axis2.transport.base.threads.Axis2ThreadPoolExecutor.<init>(Axis2ThreadPoolExecutor.java:38)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool.<init>(NativeWorkerPool.java:49)
	at org.apache.axis2.transport.base.threads.WorkerPoolFactory.getWorkerPool(WorkerPoolFactory.java:34)
	at org.apache.synapse.transport.passthru.config.BaseConfiguration.getWorkerPool(BaseConfiguration.java:154)
	at org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpSourceHandler.requestReceived(InboundHttpSourceHandler.java:94)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:273)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:114)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onInputReady(MultiListenerServerIODispatch.java:110)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onInputReady(MultiListenerServerIODispatch.java:34)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
<img width="1168" alt="image" src="https://github.com/user-attachments/assets/67fa9299-bf38-4d7a-b532-0aa5a885f0b4">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by SanojPunchihewa** [comment] 2024-08-01 04:04
Duplicate issue https://github.com/wso2/mi-vscode/issues/223

**Comment by rosensilva** [comment] 2024-08-07 08:02
can we add the validation from the UI ?

**Comment by SanojPunchihewa** [comment] 2024-08-07 08:34
@rosensilva, since we dynamically populating the form using the schema, it may not be straightforward. We may need to improve the schema and the form generator.

**Comment by thuva9872** [comment] 2024-09-04 08:42
@SanojPunchihewa , shall we close this?

**Comment by SanojPunchihewa** [comment] 2024-09-04 08:49
The original issues seems fixed. However we may need to discuss the improvement suggested by @rosensilva

**Comment by ChinthakaJ98** [comment] 2024-09-10 03:51
Closing this issue as it cannot be reproduced in the latest v1.1.0 release. Please reopen if the problem persists.

**Closed by ChinthakaJ98** 2024-09-10 03:51 UTC
Labels: Type/Improvement, Priority/Normal, Resolution/Fixed, Area/Forms
