### ISSUE TITLE
Encountered issues with CSV to CSV transformation

### ISSUE THREAD

**Issue by pcnfernando** [wso2/mi-vscode#368] opened 2024-09-03 18:10 UTC
**Description:**
A user complains of the following

> CSV to CSV transformation using the Data Mapper in the VS Code extension and encountered two issues:
> 1. How can we configure the separator for input/output samples? It currently only works with CSV files that use a comma (,) as a separator. In Integration Studio, the separator is configurable.
> 2. The input CSV sample does not load properly, although the output loads fine. I’ve attached a recording demonstrating the scenario.

https://github.com/user-attachments/assets/8158c1a8-6caa-41e1-92e5-40d312e813f2

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
Ref: https://discord.com/channels/955510916064092180/1280463817838559324

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment] 2024-09-04 17:04
> How can we configure the separator for input/output samples? It currently only works with CSV files that use a comma (,) as a separator. In Integration Studio, the separator is configurable.

A new issue has been created to track this. Please track this on https://github.com/wso2/mi-vscode/issues/373

> The input CSV sample does not load properly, although the output loads fine. I’ve attached a recording demonstrating the scenario.

This is not a bug. Please refer to the video shared on discord [1] on how to configure the datamapper for this use case.

[1]- https://discord.com/channels/955510916064092180/1280463817838559324

**Comment by thuva9872** [comment] 2024-09-04 17:06
Closing this issue as the concerns have been addressed in the previous comment.

**Comment by thuva9872** [comment] 2024-09-04 17:06
Closing this issue as the concerns have been addressed in the previous comment.

**Closed by thuva9872** 2024-09-04 17:06 UTC
Labels: Type/Bug
