### ISSUE TITLE
Minimized Micro Integrator(MI) for VS Code home page contain closely packed texts

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#240] opened 2024-07-26 13:46 UTC
**Description:**
The current minimized view displays some text that appears closely packed as indicated below.  
<img width="690" alt="Screenshot 2024-07-26 at 19 17 47" src="https://github.com/user-attachments/assets/bfff9b4c-5797-41fc-bb52-f6694411f78b">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v1.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gigara** [comment] 2024-07-29 04:57
Duplicate of https://github.com/wso2/mi-vscode/issues/17

**Closed by gigara** 2024-07-29 04:57 UTC
