### ISSUE TITLE
Logos of artifacts in the sidebar has been broken in mi-vscode v1.0.0

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#228] opened 2024-07-26 08:08 UTC
**Description:**

$title

![Screenshot 2024-07-26 at 13 36 01](https://github.com/user-attachments/assets/2e340c57-25b9-43e4-bd5f-288f1c76ea0a)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tharindulak** [comment] 2024-07-29 04:45
Icons can be found when you add artifacts to particular categories. 
These top level icons were removed since it looked too overloaded in in the activity panel.
If you observe the file explorer it also does not have icons for top level constructs.
<img width="421" alt="image" src="https://github.com/user-attachments/assets/d399ac76-0a7c-49f7-9f2e-71cbded3237b">

**Comment by gabilang** [comment] 2024-08-05 11:12
> Icons can be found when you add artifacts to particular categories. These top level icons were removed since it looked too overloaded in in the activity panel. If you observe the file explorer it also does not have icons for top level constructs. <img alt="image" width="421" src="https://private-user-images.githubusercontent.com/20821008/352916626-d399ac76-0a7c-49f7-9f2e-71cbded3237b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTY1MjgsIm5iZiI6MTcyMjg1NjIyOCwicGF0aCI6Ii8yMDgyMTAwOC8zNTI5MTY2MjYtZDM5OWFjNzYtMGE3Yy00OWY3LTlmMmUtNzFjYmRlZDMyMzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDExMTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNjFkNTYzZDY0NDI5OTliNzcxNDQzM2Y3ZjcxMDVkYjVjNjMyN2JjNGI0ZjhmMWIwNmEwM2U3MjJiYTQwZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4oYqRfAjZAdUYSxwrtrGjBUfmPCKRCHJU5oavwabyh8">

It makes sense. Thanks @tharindulak

**Comment by tharindulak** [comment] 2024-08-06 05:05
Closing this since it is not a bug

**Closed by tharindulak** 2024-08-06 05:05 UTC
Labels: Type/Bug, Area/UX, Severity/Critical, Priority/High, Resolution/Not a bug
