### ISSUE TITLE
Some fields found in documentations gives errors when used with the VSCode plugin

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#13] opened 2024-06-26 16:29 UTC
**Description:**
Several fields and attributes used in documentations give errors when used with the VSCode plugin.
1. https://mi.docs.wso2.com/en/latest/learn/examples/endpoint-examples/using-failover-endpoints/
 - Gives error "Attribute `statistics` is not allowed to appear in element endpoint" for `<endpoint name="SampleFailover" statistics="enable">`
 - Getting an error for the field `suspendOnFailure` when both `markForSuspension` and `suspendOnFailure` elements are used together as instructed in example 1.  
2. https://mi.docs.wso2.com/en/latest/learn/examples/endpoint-examples/using-loadbalancing-endpoints/
 - element `session` invalid error when `<session type="simpleClientSession"/>` used in the proxy service 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment] 2024-07-15 07:40
Hi @ShammiL ,
1. `Gives error "Attribute statistics is not allowed to appear in element endpoint" for <endpoint name="SampleFailover" statistics="enable">`
For this one, we need to add the `statistics` and `trace` in the child element only. You can check in this case, the address element has these fields. Adding these fields in the endpoint tag will not be supported by the runtime.

2. `Getting an error for the field suspendOnFailure when both markForSuspension and suspendOnFailure elements are used together as instructed in example 1.`
Related Issue: https://github.com/wso2/mi-vscode/issues/21
Please give the elements in the correct order to fix the errors. In this case the order is `timeout`, `suspendOnFailure`, `markForSuspension`, `retryConfig`.

3.  `element session invalid error when <session type="simpleClientSession"/> used in the proxy service`
  It is same as the 2nd one. We need to give the session after the endpoint definition. Please check the following configuration,

```
<endpoint>
    <!-- specify the session as the simple client session provided by Synapse for
                testing purpose -->
    <loadbalance>
        <endpoint>
            <address uri="http://localhost:9001/services/SimpleStockQuoteService">
                <enableAddressing/>
            </address>
        </endpoint>
        <endpoint>
            <address uri="http://localhost:9002/services/SimpleStockQuoteService">
                <enableAddressing/>
            </address>
        </endpoint>
        <endpoint>
            <address uri="http://localhost:9003/services/SimpleStockQuoteService">
                <enableAddressing/>
            </address>
        </endpoint>
    </loadbalance>
    <session type="simpleClientSession"/>
</endpoint>        
```

Thanks,
Thuvarakan

**Comment by thuva9872** [comment] 2024-07-26 18:18
Closing this as it is not a bug. Please reopen if you have any more concerns.

**Closed by thuva9872** 2024-07-26 18:18 UTC
Labels: Type/Bug, Severity/Major, Priority/High, Resolution/Not a bug
