### ISSUE TITLE
Micro Integrator failed on Linux Ubuntu 24.04

### ISSUE THREAD

**Issue by fpozoh** [wso2/mi-vscode#500] opened 2024-11-01 22:25 UTC
### Description

Fail when you try to create a new project. 

Error message: 

Failed to launch the language client. Please check the console for more details.

![Captura desde 2024-11-01 23-18-39](https://github.com/user-attachments/assets/84a0a5c7-61eb-41f8-9534-bf17e5133b34)

### Steps to Reproduce

1. Instal wso2 MI Visual Code Extension.
2. Try to create a new project

### Version

Visual code extension: Micro Integrator v1.1.3

### Environment Details (with versions)

          Kernel: Linux 6.8.0-48-generic
    Architecture: x86-64
 Hardware Vendor: HP
  Hardware Model: HP ProBook 455 G7

**Comment by gigara** [comment] 2024-11-04 18:36
@fpozoh Can you please attach the logs in the output window? In the output window select "Micro Integrator" from the dropdown.

**Comment by gigara** [comment] 2024-11-20 16:14
Closing since no more information is given to reproduce.

**Closed by gigara** 2024-11-20 16:14 UTC
Labels: Type/Bug, Severity/Blocker, Priority/High, Resolution/Cannot Reproduce, Area/LanguageServer
