### ISSUE TITLE
The Deactivate sequence field in the `Scheduled Message Forwarding Processor` should be marked as a required field.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#339] opened 2024-08-13 07:31 UTC
**Description:**
In the creation of the `Schedules Message Forwarding Processor`, the field to provide a `Deactivate sequence` is not required. But creating a message processor with empty value for this field and starting the server will immediately deactivate the message processor. The following log can be identified. 

```
[2024-08-13 12:56:01,306]  INFO {ScheduledMessageProcessor} - Started message processor. [ScheduledProcessor].
[2024-08-13 12:56:01,307]  INFO {AbstractQuartzTaskManager} - Task paused: [ESB_TASK][MSMP_ScheduledProcessor_0]
[2024-08-13 12:56:01,310]  INFO {ScheduledMessageProcessor} - Successfully deactivated the message processor [ScheduledProcessor]
```

Once a Deactivate Sequence is provided, it will work fine. 

**Steps to reproduce:**

**Affected Versions:**
v1.0.4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment] 2024-08-28 09:22
The `Deactivate Sequence` field is not a mandatory one. The message processor is getting deployed correctly without any issues.

**Comment by thuva9872** [comment] 2024-08-28 09:22
Closing this as it is not a bug. Please reopen if you have any concerns.

**Closed by thuva9872** 2024-08-28 09:22 UTC
Labels: Resolution/Not a bug
