### ISSUE TITLE
Deprecated mediators available in the mediator palette

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/mi-vscode#369] opened 2024-09-04 00:36 UTC
**Description:**
As confirmed with @chanikag, the following mediators are deprecated but still available in the mediator palette:

- Rule
- Publish Event
- Event
- Enqueue
- Bean
- Command
- Spring
- Conditional Router
- BAM

MI for VS Code version: v1.0.4

**Comment by thuva9872** [comment] 2024-09-04 09:20
Hi @DinithiDiaz ,

**Removed Mediators in v1.0.5:**
The following mediators have been removed from the plugin in the latest version (v1.0.5):
- Publish Event
- Event
- Enqueue
- Bean
- Command
- Spring
- Conditional Router

**Note:** The Rule and Bam mediators are not considered deprecated and therefore remain in the plugin.

The latest version (v1.0.5) is not yet available in the VS Code Marketplace. However, you can download it from [Open VSX](https://open-vsx.org/extension/wso2/micro-integrator).

Regards,
Thuvarakan

**Comment by thuva9872** [comment] 2024-09-05 05:40
Closing this as this is not a bug. Please reopen if you have any concerns.

**Closed by thuva9872** 2024-09-05 05:40 UTC
Labels: Type/Task, Resolution/Not a bug
